# Generated by Django 3.2 on 2021-05-18 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=40, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age_range_min', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('age_range_max', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('time_frame_start', models.DateField(blank=True)),
                ('time_frame_end', models.DateField(blank=True)),
                ('lessons', models.ManyToManyField(to='lessons.Lesson')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
